# Generated by Django 4.2.7 on 2023-11-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cover_picture',
            field=models.CharField(default='https://res.cloudinary.com/dxgl4eyhq/image/upload/v1701037044/huddled/images/defaults/cover_x202x0.png', max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Others')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.CharField(default='https://res.cloudinary.com/dxgl4eyhq/image/upload/v1701036989/huddled/images/defaults/profile_ioi9ke.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('s', 'Single'), ('m', 'Married'), ('d', 'Divorced'), ('c', 'Complicated')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
