# Generated by Django 4.2.7 on 2023-12-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='huddled_a1345e1e-72d8-48e1-aa5e-989b617b0faf', max_length=100, unique=True),
        ),
    ]
