# Generated by Django 4.2.7 on 2023-12-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='huddled_053fb22f-b9c1-4234-9757-ba9e61f73b01', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='huddled_fa80c08f-82b7-4d56-8f20-884b6fcee41b', max_length=100, unique=True),
        ),
    ]
