# Generated by Django 4.2.7 on 2023-12-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_id_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='huddled_user_19ff2513-b5db-42b0-8b9f-835255d8b9c5', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='huddled_cef708a0-6759-4ea1-afe7-31820c85e03d', max_length=100, unique=True),
        ),
    ]
