# Generated by Django 4.2.7 on 2023-12-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customuser_middle_name_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='huddled_user_278c5cc2-5e81-46a4-9ba9-c26abb5217d9', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='huddled_6777ed8c-7390-4144-bf95-5eb84f2341a7', max_length=100, unique=True),
        ),
    ]
