# Generated by Django 4.2.7 on 2023-12-17 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_id_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='huddled_user_a0c4f91f-ed05-47e5-8c51-370b26662e16', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='huddled_1ca7342c-887e-4861-af8f-dafe1e2d2d00', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='UserCoverPicture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_pictures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
