# Generated by Django 4.2.7 on 2023-12-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_id_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='huddled_user_76cd98cc-16c6-4b1d-9605-c0690e020ba6', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='huddled_ec453161-5a47-4e16-ba1f-6857414943e9', max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='UserCoverPicture',
        ),
    ]
