# Generated by Django 4.2.7 on 2023-12-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_profile_picture_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='huddled_user_be884d2c-f47c-4fd0-8739-3bbc2f1cf905', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='huddled_2e3ed2ee-c45b-4679-89e0-aad10e73d17d', max_length=100, unique=True),
        ),
    ]
