# Generated by Django 4.2.7 on 2023-12-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_huddled_verified',
            field=models.BooleanField(default=False),
        ),
    ]
